/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        brown: {
          100: "#F3E8E4",
          200: "#E4C8B8",
          300: "#D5A88C",
          400: "#C68960",
          500: "#914F1E",
          600: "#803F19",
          700: "#6F3014",
          800: "#5D210F",
          900: "#4C130A",
        },
        peach: {
          100: "#FBF2E7",
          200: "#F6DEC2",
          300: "#F0C99C",
          400: "#EBB577",
          500: "#DEAC80",
          600: "#C59973",
          700: "#AC8565",
          800: "#937257",
          900: "#7A5F4A",
        },
        beige: {
          100: "#FEF8F1",
          200: "#FDF0E2",
          300: "#FCE8D4",
          400: "#FBE0C5",
          500: "#F7DCB9",
          600: "#E8C7A6",
          700: "#D9B193",
          800: "#CA9C80",
          900: "#BB866D",
        },
        green: {
          100: "#F3F7EB",
          200: "#E3ECD0",
          300: "#D3E0B4",
          400: "#C3D599",
          500: "#B5C18E",
          600: "#A1A87B",
          700: "#8D8F69",
          800: "#797656",
          900: "#655D44",
        },
      },
      fontFamily: {
        "nunito-black": ["Nunito-Black", "sans-serif"],
        "nunito-black-italic": ["Nunito-BlackItalic", "sans-serif"],
        "nunito-bold": ["Nunito-Bold", "sans-serif"],
        "nunito-bold-italic": ["Nunito-BoldItalic", "sans-serif"],
        "nunito-extra-bold": ["Nunito-ExtraBold", "sans-serif"],
        "nunito-extra-bold-italic": ["Nunito-ExtraBoldItalic", "sans-serif"],
        "nunito-extra-light": ["Nunito-ExtraLight", "sans-serif"],
        "nunito-extra-light-italic": ["Nunito-ExtraLightItalic", "sans-serif"],
        "nunito-italic": ["Nunito-Italic", "sans-serif"],
        "nunito-light": ["Nunito-Light", "sans-serif"],
        "nunito-light-italic": ["Nunito-LightItalic", "sans-serif"],
        "nunito-medium": ["Nunito-Medium", "sans-serif"],
        "nunito-medium-italic": ["Nunito-MediumItalic", "sans-serif"],
        "nunito-regular": ["Nunito-Regular", "sans-serif"],
        "nunito-semi-bold": ["Nunito-SemiBold", "sans-serif"],
        "nunito-semi-bold-italic": ["Nunito-SemiBoldItalic", "sans-serif"],
      },
    },
  },
  plugins: [],
};
